name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore main project
      run: dotnet restore "library.mvc/library.mvc.csproj"

    - name: Restore test project
      run: dotnet restore "xUnit Test Project/library.mvc.Tests.csproj"

    - name: Build main project
      run: dotnet build "library.mvc/library.mvc.csproj" --no-restore --configuration Release

    - name: Build test project
      run: dotnet build "xUnit Test Project/library.mvc.Tests.csproj" --no-restore --configuration Release

    - name: Test
      run: dotnet test "xUnit Test Project/library.mvc.Tests.csproj" --no-build --configuration Release